apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  template:
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        - name: VERSION
          value: v0.0.1
        image: localhost:5001/product-service:v0.0.1
        name: ""
        ports:
        - containerPort: 8080
        resources: {}
status: {}
