apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: product-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/updateTimestamp: "2024-12-21T17:42:17Z"
        client.knative.dev/user-image: product-service
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        image: kind.local/product-service
        imagePullPolicy: Never
        name: ""
        ports:
        - containerPort: 8080
        resources: {}
status: {}
