apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        - name: VERSION
          value: v0.2.0
        image: localhost:5001/customer-service:v0.2.0
        name: ""
        ports:
        - containerPort: 8080
        resources: {}
status: {}
