apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: customer
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092
  topics:
   - customer
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: customer-service
    uri: /customers/blockAmount