apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: order
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092
  topics:
   - order
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-service
    uri: /orders/confirm