apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: product
spec:
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092
  topics:
   - product
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: product-service
    uri: /products/block